version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: judges-postgres
    environment:
      POSTGRES_DB: judges_management_local
      POSTGRES_USER: judges_user
      POSTGRES_PASSWORD: local_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U judges_user -d judges_management_local"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: